import { TravelPackage,Destination, Testimonial, BlogPost } from "@/types";

export const POPULAR_PACKAGES: TravelPackage[] = [
  {
    id: "maldives-paradise",
    title: "Maldives Beach Paradise",
    destination: "Maldives",
    country: "Maldives",
    duration: "05 Days",
    pricePerPerson: 399,
    isHotSale: true,
    images: ["/assets/img/home1/tour-package-img1.jpg"],
    category: "popular",
    experience: "Including Activities Scuba Diving, Zip-lining, Rafting & Rock Climbing.",
    inclusion: "Accommodation, Daily Meals, Entry Fees & Local Transfers.",
  },
  {
    id: "bali-paradise",
    title: "Bali Paradise Tour",
    destination: "Indonesia",
    country: "Indonesia",
    duration: "07 Days",
    pricePerPerson: 599,
    isHotSale: true,
    images: ["/assets/img/home1/tour-package-img2.jpg"],
    category: "popular",
    experience: "Including Activities Scuba Diving, Zip-lining, Rafting & Rock Climbing.",
    inclusion: "Accommodation, Daily Meals, Entry Fees & Local Transfers.",
  },
  {
    id: "phuket-krabi",
    title: "Phuket & Krabi Island",
    destination: "Thailand",
    country: "Thailand",
    duration: "08 Days",
    pricePerPerson: 499,
    images: ["/assets/img/home1/tour-package-img3.jpg"],
    category: "popular",
    experience: "Including Activities Scuba Diving, Zip-lining, Rafting & Rock Climbing.",
    inclusion: "Accommodation, Daily Meals, Entry Fees & Local Transfers.",
  },
  {
    id: "rome-florence-venice",
    title: "Rome, Florence & Venice",
    destination: "Italy, France",
    country: "Italy",
    duration: "06 Days/07 Nights",
    pricePerPerson: 999,
    isHotSale: true,
    images: ["/assets/img/home1/tour-package-img4.jpg"],
    category: "popular",
    experience: "Including Activities Scuba Diving, Zip-lining, Rafting & Rock Climbing.",
    inclusion: "Accommodation, Daily Meals, Entry Fees & Local Transfers.",
  },
  {
    id: "egypt-nile-cruise",
    title: "Egypt & Nile Cruise Adventure",
    destination: "Egypt",
    country: "Egypt",
    duration: "10 Days",
    pricePerPerson: 499,
    images: ["/assets/img/home1/tour-package-img5.jpg"],
    category: "popular",
    experience: "Including Activities Scuba Diving, Zip-lining, Rafting & Rock Climbing.",
    inclusion: "Accommodation, Daily Meals, Entry Fees & Local Transfers.",
  },
  {
    id: "norway-northern-lights",
    title: "Norway Northern Lights",
    destination: "Norway",
    country: "Norway",
    duration: "07 Days/06 Nights",
    pricePerPerson: 359,
    isHotSale: true,
    images: ["/assets/img/home1/tour-package-img6.jpg"],
    category: "popular",
    experience: "Including Activities Scuba Diving, Zip-lining, Rafting & Rock Climbing.",
    inclusion: "Accommodation, Daily Meals, Entry Fees & Local Transfers.",
  },
];

export const LAST_MINUTE_PACKAGES: TravelPackage[] = [
  {
    id: "japan-cherry-blossom",
    title: "Japan Cherry Blossom",
    destination: "Tokyo, Japan",
    country: "Japan",
    duration: "06 Days",
    pricePerPerson: 399,
    originalPrice: 999,
    isHotSale: true,
    images: ["/assets/img/home1/tour-package-img7.jpg"],
    category: "lastMinute",
    experience: "Including Activities Scuba Diving, Zip-lining, Rafting & Rock Climbing.",
    inclusion: "Accommodation, Daily Meals, Entry Fees & Local Transfers.",
  },
  {
    id: "abu-dhabi-luxury",
    title: "Abu Dhabi Luxury Escape",
    destination: "UAE, Qatar",
    country: "UAE",
    duration: "05 Days/04 Nights",
    pricePerPerson: 720,
    originalPrice: 899,
    discountPercent: 20,
    images: ["/assets/img/home1/tour-package-img8.jpg"],
    category: "lastMinute",
    experience: "Including Activities Scuba Diving, Zip-lining, Rafting & Rock Climbing.",
    inclusion: "Accommodation, Daily Meals, Entry Fees & Local Transfers.",
  },
  {
    id: "morocco-desert",
    title: "Morocco Desert & City Adventure",
    destination: "Europe",
    country: "Morocco",
    duration: "07 Days/06 Nights",
    pricePerPerson: 339,
    originalPrice: 399,
    discountPercent: 15,
    images: ["/assets/img/home1/tour-package-img9.jpg"],
    category: "lastMinute",
    experience: "Including Activities Scuba Diving, Zip-lining, Rafting & Rock Climbing.",
    inclusion: "Accommodation, Daily Meals, Entry Fees & Local Transfers.",
  },
];

export const ONE_DAY_TRIPS: TravelPackage[] = [
  {
    id: "hanoi-kiem-lake",
    title: "Hanoi Kiem Lake",
    destination: "Hanoi, Vietnam",
    country: "Vietnam",
    duration: "1 Day",
    pricePerPerson: 99,
    isHotSale: true,
    images: ["/assets/img/home1/tour-package-img10.jpg"],
    category: "oneDay",
    experience: "Including Activities Scuba Diving, Zip-lining, Rafting & Rock Climbing.",
    inclusion: "Accommodation, Daily Meals, Entry Fees & Local Transfers.",
  },
  {
    id: "newlands-safari",
    title: "Newlands Safari Forest",
    destination: "South Africa",
    country: "South Africa",
    duration: "1 Day",
    pricePerPerson: 89,
    images: ["/assets/img/home1/tour-package-img11.jpg"],
    category: "oneDay",
    experience: "Including Activities Scuba Diving, Zip-lining, Rafting & Rock Climbing.",
    inclusion: "Accommodation, Daily Meals, Entry Fees & Local Transfers.",
  },
  {
    id: "ho-chi-minh-saigon",
    title: "Ho Chi Minh City (Saigon)",
    destination: "Saigon, Vietnam",
    country: "Vietnam",
    duration: "1 Day",
    pricePerPerson: 69,
    isHotSale: true,
    images: ["/assets/img/home1/tour-package-img12.jpg"],
    category: "oneDay",
    experience: "Including Activities Scuba Diving, Zip-lining, Rafting & Rock Climbing.",
    inclusion: "Accommodation, Daily Meals, Entry Fees & Local Transfers.",
  },
  {
    id: "norway-northern-lights-day",
    title: "Norway Northern Lights",
    destination: "Norway",
    country: "Norway",
    duration: "1 Day",
    pricePerPerson: 89,
    isHotSale: true,
    images: ["/assets/img/home1/tour-package-img6.jpg"],
    category: "oneDay",
    experience: "Including Activities Scuba Diving, Zip-lining, Rafting & Rock Climbing.",
    inclusion: "Accommodation, Daily Meals, Entry Fees & Local Transfers.",
  },
  {
    id: "rome-day",
    title: "Rome, Florence & Venice",
    destination: "Europe",
    country: "Italy",
    duration: "1 Day",
    pricePerPerson: 49,
    images: ["/assets/img/home1/tour-package-img4.jpg"],
    category: "oneDay",
    experience: "Including Activities Scuba Diving, Zip-lining, Rafting & Rock Climbing.",
    inclusion: "Accommodation, Daily Meals, Entry Fees & Local Transfers.",
  },
];

export const FEATURED_DESTINATIONS: Destination[] = [
  { id: "rome", name: "Rome, Italy", country: "Italy", region: "Europe", image: "/assets/img/home1/destination-img1.jpg", tourCount: 140, departureCount: 240, guestCount: 15786 },
  { id: "paris", name: "Paris, France", country: "France", region: "Europe", image: "/assets/img/home1/destination-img2.jpg", tourCount: 140, departureCount: 240, guestCount: 15786 },
  { id: "switzerland", name: "Switzerland", country: "Switzerland", region: "Europe", image: "/assets/img/home1/destination-img3.jpg", tourCount: 120, departureCount: 250, guestCount: 15786 },
  { id: "scotland", name: "Scotland, UK", country: "UK", region: "Europe", image: "/assets/img/home1/destination-img4.jpg", tourCount: 110, departureCount: 230, guestCount: 15786 },
  { id: "athens", name: "Athens, Greece", country: "Greece", region: "Europe", image: "/assets/img/home1/destination-img5.jpg", tourCount: 70, departureCount: 150, guestCount: 15786 },
  { id: "istanbul", name: "Istanbul, Turkey", country: "Turkey", region: "Europe", image: "/assets/img/home1/destination-img6.jpg", tourCount: 120, departureCount: 230, guestCount: 15786 },
];

export const TESTIMONIALS: Testimonial[] = [
  { id: "1", name: "Robert Kcarery", role: "GoFly Traveler", avatar: "/assets/img/home1/testimonial-author-img1.png", rating: 5, title: "Excellent Tourist Place!", review: "Our honeymoon package to the Maldives was beyond amazing! The travel agency took care of every detail." },
  { id: "2", name: "Selina Henry", role: "GoFly Traveler", avatar: "/assets/img/home1/testimonial-author-img2.png", rating: 5, title: "Great Experience!", review: "This was the best trip of my life! Everything was perfectly planned, from airport pickup to guided tours. Highly recommended!" },
  { id: "3", name: "James Bonde", role: "GoFly Traveler", avatar: "/assets/img/home1/testimonial-author-img3.png", rating: 4, title: "Average Experience", review: "The tour was well-organized, and we enjoyed every bit of it. However, I wish we had more free time to explore on our own." },
  { id: "4", name: "Michael D Linda", role: "GoFly Traveler", avatar: "/assets/img/home1/testimonial-author-img4.png", rating: 5, title: "Great Visitors Venue!", review: "Thank you so much for your work on our honeymoon. We really did have such a great time!" },
  { id: "5", name: "Amber Lashley", role: "GoFly Traveler", avatar: "/assets/img/home1/testimonial-author-img5.png", rating: 5, title: "Fantastic Service!", review: "We have returned from Greece and want to let you know how terrific the trip was! Everything was great." },
];

export const BLOG_POSTS: BlogPost[] = [
  { id: "1", location: "Tokyo, Japan", title: "Top 10 Beaches to Visit This Summer Season.", date: "31 January, 2025", excerpt: "Famous for its pure white silica sand & crystal-clear waters. Perfect for snorkeling & sailing!", image: "/assets/img/home1/blog-img1.jpg", href: "/travel-inspiration/details" },
  { id: "2", location: "Vietnam", title: "Tropical Escapes & Beach Getaways.", date: "23 January, 2025", excerpt: "A beach getaway is perfect for those seeking relaxation, adventure, or a romantic retreat.", image: "/assets/img/home1/blog-img2.jpg", href: "/travel-inspiration/details" },
  { id: "3", location: "Maldives", title: "Crystal-Clear Waters & White Sands.", date: "01 April, 2025", excerpt: "Perfect for couples, families, and solo travelers alike, these beach destinations promise relaxation.", image: "/assets/img/home1/blog-img3.jpg", href: "/travel-inspiration/details" },
  { id: "4", location: "Bali, Indonesia", title: "Escape to the World's Breathtaking Islands.", date: "23 March, 2025", excerpt: "Escape to the World's Most Breathtaking Islands and immerse yourself in paradise.", image: "/assets/img/home1/blog-img4.jpg", href: "/travel-inspiration/details" },
];

export const DESTINATION_REGIONS = ["Europe", "Asia", "Middle East", "Africa", "North America", "Oceania"] as const;

export const QUICK_SEARCH_TAGS = [
  "Thailand Tour",
  "Philippines Tour",
  "Bali Tour",
  "Hawaii, USA Tour",
  "Switzerland Tour",
  "Maldives Tour",
  "Paris Tour",
];

export const FAQ_ITEMS = [
  {
    question: "What services does your travel agency provide?",
    answer: "A travel agency typically provides a wide range of services to ensure a smooth and enjoyable travel experience. As like — Hotel booking, Flight Booking, Visa & Customized Travel Package etc.",
  },
  {
    question: "Do you offer customized travel packages?",
    answer: "Absolutely! We offer fully customized travel packages based on your interests, budget, and schedule. Whether you're planning a solo adventure, a family vacation, a romantic getaway, or a group tour.",
  },
  {
    question: "Can I book flights, hotels, and tours separately?",
    answer: "Yes, you can! We provide the flexibility to book flights, hotels, and tours separately based on your specific needs.",
  },
  {
    question: "Do you provide visa assistance?",
    answer: "Yes, we do! Our team offers complete visa assistance services to help you navigate the application process smoothly.",
  },
  {
    question: "What payment methods do you accept?",
    answer: "We accept a variety of payment methods including cash, bank transfers, mobile payments (such as bKash, Nagad), and major debit/credit cards.",
  },
  {
    question: "What travel documents are required for international travel?",
    answer: "For international travel, you'll typically need a valid passport, visa (if required), airline tickets, travel insurance, and any health certificates.",
  },
];
